### ISSUE TITLE
[ERROR] [OBDOverCANModule.cpp:360] [autoDetectECUs()]: [Failed to write]

### ISSUE THREAD

**Issue by Atharva01** [aws/aws-iot-fleetwise-edge#102]
# Issue: Error When Running AWS IoT FleetWise Campaign on Raspberry Pi

## Description

I am trying to implement **AWS IoT FleetWise** using Raspberry Pi, following the [Raspberry Pi Tutorial](https://github.com/aws/aws-iot-fleetwise-edge/blob/main/docs/rpi-tutorial/raspberry-pi-tutorial.md).

- **Development machine**: AWS EC2 (`m6g.large`)
- **Edge agent**: Raspberry Pi

This problem occurs when running the `demo.sh` script to start the campaign.

### Command:
```bash
./demo.sh --vehicle-name fwdemo-rpi --campaign-file campaign-obd-heartbeat.json
```
### Screenshot of demo.sh:
![Error on development machine](https://github.com/user-attachments/assets/f4c09f04-e7d9-4a3f-b6ae-1216512c3efd)

### Screenshot of Service Running on Edge Agent:
![Service: fwe@0 running on Edge Agent](https://github.com/user-attachments/assets/2caf8d03-83f1-41b5-a305-50532f8ca02e)

## Data Source

I have used both **CANsim** and an actual car to feed data into the CANBus of the Raspberry Pi, but the result is the same in both cases. (https://github.com/aws/aws-iot-fleetwise-edge/tree/main/tools/cansim)

## Expected Behavior
The campaign should start successfully and collect data without errors.

**Comment by Atharva01** [comment]
Please feel free to add your suggestions.

**Comment by nenadilic84** [comment]
Hi @Atharva01, thanks for creating the issue. It seems that you might have an issue with the CAN setup. Can you verify if the CAN interface is up and that your providing the right interface to the provisioning script as well. 

I assume you are using the CAN Bus Expansion HAT, if so there was a comment in one of the closed issues on how to test it:
https://github.com/aws/aws-iot-fleetwise-edge/issues/100#issuecomment-2360562412

Let me know if this helps

**Comment by Atharva01** [comment]
Hello @nenadilic84 , thanks for sharing #100, I am using the same CAN Bus Expansion hat as per the instructions in the repo.
I will follow the steps mentioned in previously resolved issue, you shared.

**Comment by Atharva01** [comment]
Hi @nenadilic84, I followed #100 and data is populated in TimeStream Database as well as in the JSON file under collected-data folder. Looking at the messages generated by the cansim script, CAN Messages are 11 bits long. Does AWS FWE only supports 11 bits CAN Message or it can extend support to 29 bit CAN Messages as well? I replayed the stored CAN Messages from a car on can0 and ran the demo script and same error occurred.

**Comment by nenadilic84** [comment]
The 29-bit is supported. Take a look [here](https://github.com/aws/aws-iot-fleetwise-edge/blob/f71c9e7e684c9f2d638500d63cc20f7f669b5ad0/src/OBDOverCANModule.cpp#L397-L398).
Make sure that the decoder manifest and the signal catalog is aligned with the signals you have on the CAN.

**Comment by nenadilic84** [comment]
@Atharva01 any news on this? Should we close the issue?
