### ISSUE TITLE
Provisioning fails when using S3 Bucket is us-east-1 

### ISSUE THREAD

**Issue by svisagie** [aws/aws-iot-fleetwise-edge#55]
As per the S3 API documentation, 'aws s3api get-bucket-location' call returns a LocationConstraint = null if a bucket is located in us-east-1 region, so the code below should be updated to the the S3_BUCKET_REGION = us-east-1 if null is returned from s3api call

https://github.com/aws/aws-iot-fleetwise-edge/blob/a5a0d9f26fb08befe1c0c909345f4157e774ae79/tools/android-app/cloud/provision.sh#L75

**Comment by ruhland** [comment]
Thanks a lot for finding this issue!
I created a fix to default to us-east-1 if null. As you pointed out only us-east-1 should return null

**Comment by ruhland** [comment]
The PR https://github.com/aws/aws-iot-fleetwise-edge/pull/56 was merged to main so I am closing this. I the error persists please reopen or open another issue. And thanks again for debugging and reporting this issue.
