### ISSUE TITLE
E: Unable to locate package clang-format-10 E: Unable to locate package clang-tidy-10

### ISSUE THREAD

**Issue by Starkeus** [aws/aws-iot-fleetwise-edge#82]
I think the packages being installed for the following are not connected to clang-format-10 and clang-tidy-10. Is there a workaround?
ksriram@CustomHPC:~/aws-iot-fleetwise-edge$ sudo -H ./tools/install-deps-native.sh \
&& sudo -H ./tools/install-socketcan.sh \
&& sudo -H ./tools/install-cansim.sh
Hit:1 http://packages.microsoft.com/repos/code stable InRelease
Hit:2 http://us.archive.ubuntu.com/ubuntu jammy InRelease                                                                                                                        
Hit:3 http://packages.ros.org/ros2/ubuntu jammy InRelease                                                                                                                        
Hit:4 https://download.docker.com/linux/ubuntu jammy InRelease                                                                                                                   
Get:5 http://us.archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]                                                                  
Get:6 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]                                                                            
Hit:7 http://us.archive.ubuntu.com/ubuntu jammy-backports InRelease                                                                                              
Get:8 http://us.archive.ubuntu.com/ubuntu jammy-updates/main i386 Packages [570 kB]              
Hit:9 http://www.peak-system.com/debian wheezy InRelease                                         
Get:10 http://us.archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [1,377 kB]
Hit:11 https://ppa.launchpadcontent.net/wireshark-dev/stable/ubuntu jammy InRelease
Get:12 http://us.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1,049 kB]
Get:13 http://us.archive.ubuntu.com/ubuntu jammy-updates/universe i386 Packages [689 kB]
Get:14 http://us.archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 Packages [42.1 kB]
Get:15 http://us.archive.ubuntu.com/ubuntu jammy-updates/multiverse i386 Packages [4,184 B]
Fetched 3,961 kB in 2s (1,716 kB/s)                            
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
373 packages can be upgraded. Run 'apt list --upgradable' to see them.
W: http://www.peak-system.com/debian/dists/wheezy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package clang-format-10
E: Unable to locate package clang-tidy-10

**Comment by hefroy** [comment]
Hi @Starkeus, thanks for your bug report. Our officially supported OS is currently Ubuntu 20.04 (Focal), whereas I see you are using Ubuntu 22.04 (Jammy). While we won't officially support Ubuntu 22.04 until April 2025 (the EOL date for 20.04), I've opened #83 that updates the version of `clang-format` and `clang-tidy` to v12, which is available in Ubuntu 22.04. (Even with this change, `tools/install-deps-native.sh` still won't support the `--with-ros2-support` in case you were trying to use that.)

**Comment by hefroy** [comment]
Resolving as fixed by #83. Please re-open if you have any further issues.
