### ISSUE TITLE
boost 1.85 filesystem extension deprecation

### ISSUE THREAD

**Issue by thomas-roos** [aws/aws-iot-fleetwise-edge#90]
1.1.1 does not compile with boost 1.85 since filesystem extension is deprecated.

Patch: 
[boost_filesystem_extension.patch.txt](https://github.com/user-attachments/files/15877012/boost_filesystem_extension.patch.txt)

**Comment by hefroy** [comment]
Fixed with v1.1.2: aa07b246f089b1252e83c40eb2af1e43c3a99967
